In [89]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [90]:
df = pd.read_csv('insurance_data.csv')
df.head(10)

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1
5   56              1                 1
6   55              0                 0
7   60              0                 1
8   62              1                 1
9   61              1                 1

In [91]:
X_train,X_test,y_train,y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,random_state=25,test_size=0.2)

In [ ]:
# Scaled Data
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
#X_train_scaled = X_train.copy()
X_train_scaled = scaler.fit_transform(X_train) # learn + apply
X_test_scaled = scaler.transform(X_test)

# convert back to data frame from numpy array and preserving the indexes and labels
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test_scaled  = pd.DataFrame(X_test_scaled,  columns=X_test.columns,  index=X_test.index)

In [97]:
X_test_scaled

         age  affordibility
2   0.659091            1.0
10  0.000000            1.0
21  0.181818            0.0
11  0.227273            1.0
14  0.704545            1.0
9   0.977273            1.0

In [98]:
y_train

0     0
13    0
6     0
17    1
24    1
19    0
25    1
16    1
20    0
3     0
7     1
1     0
5     1
27    0
8     1
18    0
12    0
23    1
22    1
15    1
26    0
4     1
Name: bought_insurance, dtype: int64

In [93]:

def sigmoid(X):
    return 1/(1+np.exp(-X))

In [94]:
y_train.shape

(22,)

In [95]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 =1 
        self.b = 0

    def log_loss(self,y_true,y_predicted):
        epsilon = 1e-15
        y_predicted_new  = [max(i,epsilon) for i in y_predicted]
        y_predicted_new  = [min(i,1-epsilon) for i in y_predicted_new]
        y_predicted_new = np.array(y_predicted_new)
        loss = -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)* np.log(1-y_predicted_new))
        return loss
    
    def predict(self,X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility']+ self.b
        return sigmoid(weighted_sum)
        
    def fit(self,X,y,epochs,loss_threshold):
        self.w1, self.w2 , self.b = self.gradient_Descent(X['age'],X['affordibility'],y,epochs,loss_threshold)
        print(f'Final weights and bias: w1:{self.w1},w2:{self.w2}, bias: {self.b}')
        
    def gradient_Descent(self,age,affordibility,y_true,epochs,loss_threshold):
        w1 =w2 = 1
        bias = 0 
        lr =0.01
        n = len(age)

        for i  in range (epochs):
            weighted_sum = w1* age + w2*affordibility + bias
            y_predicted = sigmoid(weighted_sum)
            loss = self.log_loss(y_true,y_predicted)

            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted- y_true ))
            w2d = (1/n)* np.dot(np.transpose(affordibility),(y_predicted - y_true))
            bias_d = np.mean((y_predicted - y_true))

            w1 = w1 - lr* w1d
            w2 = w2 - lr*w2d
            bias = bias-lr*bias_d

            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_threshold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1,w2,bias

In [96]:
customModel = myNN()
customModel.fit(X_train_scaled,y_train, epochs = 8000,loss_threshold= 0.4631)

Epoch:0, w1:0.9996015344952567, w2:0.9988672092854675, bias:-0.0024068773460263998, loss:0.6864577089444572
Epoch:50, w1:0.9829513996260844, w2:0.9465638744172128, bias:-0.11573507710048425, loss:0.6545703543538669
Epoch:100, w1:0.9724535087258895, w2:0.9024892687959608, bias:-0.21597665016681997, loss:0.6302249407410225
Epoch:150, w1:0.9676001086913584, w2:0.8660578819770086, bias:-0.30430686061988615, loss:0.6118065792875161
Epoch:200, w1:0.9677869399294342, w2:0.8365239074865054, bias:-0.38203623821806043, loss:0.5978930948369044
Epoch:250, w1:0.9723730839313265, w2:0.8130691847582731, bias:-0.450500199497553, loss:0.5873132546291546
Epoch:300, w1:0.9807270282456123, w2:0.7948720497307843, bias:-0.5109793140633477, loss:0.5791504712089254
Epoch:350, w1:0.9922572431248114, w2:0.7811538721854226, bias:-0.5646501482127158, loss:0.5727146791060052
Epoch:400, w1:1.0064292536137822, w2:0.7712058674891273, bias:-0.6125609909493369, loss:0.567501306120414
Epoch:450, w1:1.0227726031209368, w2:0.7644010326588228, bias:-0.6556252152601126, loss:0.5631493923239435
Epoch:500, w1:1.0408810831897373, w2:0.7601961012570613, bias:-0.6946257571610212, loss:0.5594048678988015
Epoch:550, w1:1.0604089548983764, w2:0.758127487594424, bias:-0.7302257528837593, loss:0.5560910024108453
Epoch:600, w1:1.08106511185748, w2:0.757804066259575, bias:-0.7629819474034581, loss:0.5530858852585525
Epoch:650, w1:1.102606462521665, w2:0.7588986557252203, bias:-0.7933587528341728, loss:0.5503058827655004
Epoch:700, w1:1.1248313056675865, w2:0.7611393428194985, bias:-0.821741738449227, loss:0.5476937933169506
Epoch:750, w1:1.147573127001934, w2:0.764301283009067, bias:-0.8484499300706003, loss:0.5452105203347505
Epoch:800, w1:1.1706950220468095, w2:0.7681992883761134, bias:-0.8737466661684258, loss:0.5428292956794656
Epoch:850, w1:1.19408481466963, w2:0.7726813181352846, bias:-0.8978489737825985, loss:0.540531711233672
Epoch:900, w1:1.2176508627479488, w2:0.777622873101195, bias:-0.9209355442200129, loss:0.5383050122137036
Epoch:950, w1:1.2413185014162742, w2:0.7829222351425404, bias:-0.9431534444245775, loss:0.5361402608194458
Epoch:1000, w1:1.2650270558309207, w2:0.7884964647054594, bias:-0.9646237199276712, loss:0.5340310951936129
Epoch:1050, w1:1.2887273500987937, w2:0.7942780605699213, bias:-0.9854460451461077, loss:0.5319728930411188
Epoch:1100, w1:1.312379641069992, w2:0.8002121876964463, bias:-1.005702566180337, loss:0.5299622090500138
Epoch:1150, w1:1.3359519114829177, w2:0.8062543861664531, bias:-1.02546106593828, loss:0.5279963969444792
Epoch:1200, w1:1.3594184643209846, w2:0.812368683743596, bias:-1.0447775646804704, loss:0.5260733557332288
Epoch:1250, w1:1.3827587679543112, w2:0.8185260447173236, bias:-1.0636984527596673, loss:0.5241913593532537
Epoch:1300, w1:1.4059565090247532, w2:0.8247030974684657, bias:-1.0822622373214241, loss:0.5223489422456331
Epoch:1350, w1:1.4289988167566825, w2:0.8308810921391165, bias:-1.1005009714225695, loss:0.5205448224165147
Epoch:1400, w1:1.4518756283083625, w2:0.8370450476997147, bias:-1.1184414224946797, loss:0.5187778496112172
Epoch:1450, w1:1.4745791699033055, w2:0.8431830545510719, bias:-1.1361060272521009, loss:0.5170469703121612
Epoch:1500, w1:1.4971035328423523, w2:0.8492857046312607, bias:-1.1535136718639474, loss:0.5153512040102927
Epoch:1550, w1:1.5194443271690965, w2:0.8553456259116102, bias:-1.170680329291844, loss:0.5136896270348358
Epoch:1600, w1:1.5415983988282114, w2:0.8613571022732365, bias:-1.1876195799522338, loss:0.5120613614547618
Epoch:1650, w1:1.5635635987022856, w2:0.8673157631670921, bias:-1.2043430371168866, loss:0.5104655673874366
Epoch:1700, w1:1.5853385940168834, w2:0.8732183302810486, bias:-1.2208606945587457, loss:0.5089014375998486
Epoch:1750, w1:1.6069227143361413, w2:0.8790624107611392, bias:-1.2371812107429812, loss:0.5073681936557001
Epoch:1800, w1:1.628315825794136, w2:0.8848463284430882, bias:-1.2533121412355497, loss:0.5058650831078079
Epoch:1850, w1:1.6495182283733152, w2:0.8905689861153332, bias:-1.2692601288523402, loss:0.504391377399994
Epoch:1900, w1:1.6705305719954375, w2:0.8962297531158205, bias:-1.2850310593161673, loss:0.5029463702529582
Epoch:1950, w1:1.6913537879701253, w2:0.9018283736121946, bias:-1.3006301887557274, loss:0.5015293763825281
Epoch:2000, w1:1.7119890329827772, w2:0.907364891770454, bias:-1.316062248211635, loss:0.500139730448221
Epoch:2050, w1:1.732437643323009, w2:0.9128395907154663, bias:-1.331331529361551, loss:0.4987767861632815
Epoch:2100, w1:1.7527010974784238, w2:0.918252942756457, bias:-1.346441954899548, loss:0.497439915519681
Epoch:2150, w1:1.7727809855639025, w2:0.9236055688153325, bias:-1.361397136371746, loss:0.4961285080965443
Epoch:2200, w1:1.792678984338183, w2:0.9288982053746709, bias:-1.3762004217543264, loss:0.4948419704305646
Epoch:2250, w1:1.8123968367889813, w2:0.9341316775713032, bias:-1.3908549346395829, loss:0.4935797254337515
Epoch:2300, w1:1.831936335455018, w2:0.9393068773134458, bias:-1.4053636065530144, loss:0.49234121184843455
Epoch:2350, w1:1.8512993088058363, w2:0.9444247455049196, bias:-1.4197292036451086, loss:0.49112588373253935
Epoch:2400, w1:1.8704876101246588, w2:0.9494862576276935, bias:-1.4339543487737445, loss:0.48993320997023615
Epoch:2450, w1:1.8895031084409617, w2:0.9544924120707932, bias:-1.448041539807415, loss:0.48876267380448296
Epoch:2500, w1:1.9083476811421995, w2:0.959444220705295, bias:-1.4619931648279447, loss:0.48761377238894427
Epoch:2550, w1:1.9270232079616119, w2:0.9643427012962672, bias:-1.475811514787774, loss:0.4864860163574212
Epoch:2600, w1:1.9455315660941974, w2:0.9691888714169585, bias:-1.4894987940759374, loss:0.4853789294093792
Epoch:2650, w1:1.9638746262378963, w2:0.9739837435913391, bias:-1.5030571293644759, loss:0.4842920479104673
Epoch:2700, w1:1.9820542493938322, w2:0.97872832144078, bias:-1.5164885770397096, loss:0.4832249205071386
Epoch:2750, w1:2.0000722842894745, w2:0.9834235966512739, bias:-1.529795129467788, loss:0.48217710775462697
Epoch:2800, w1:2.0179305653131587, w2:0.9880705466108107, bias:-1.5429787202989689, loss:0.48114818175764834
Epoch:2850, w1:2.035630910868489, w2:0.9926701325936916, bias:-1.5560412289783012, loss:0.4801377258232623
Epoch:2900, w1:2.0531751220735535, w2:0.9972232983908019, bias:-1.5689844846003076, loss:0.47914533412539834
Epoch:2950, w1:2.070564981743404, w2:1.0017309693030587, bias:-1.58181026922063, loss:0.4781706113805775
Epoch:3000, w1:2.0878022536051626, w2:1.0061940514301733, bias:-1.5945203207174334, loss:0.47721317253441065
Epoch:3050, w1:2.1048886817042485, w2:1.0106134311990587, bias:-1.6071163352788627, loss:0.476272642458467
Epoch:3100, w1:2.121825989967552, w2:1.0149899750862588, bias:-1.6195999695792809, loss:0.4753486556571353
Epoch:3150, w1:2.1386158818954666, w2:1.0193245294969524, bias:-1.6319728426959454, loss:0.47444085598411634
Epoch:3200, w1:2.1552600403596793, w2:1.0236179207698417, bias:-1.6442365378086552, loss:0.4735488963682047
Epoch:3250, w1:2.1717601274876643, w2:1.0278709552827476, bias:-1.6563926037174326, loss:0.4726724385480255
Epoch:3300, w1:2.1881177846182642, w2:1.0320844196382868, bias:-1.6684425562071756, loss:0.4718111528154131
Epoch:3350, w1:2.2043346323153843, w2:1.036259080912709, bias:-1.6803878792831761, loss:0.4709647177671259
Epoch:3400, w1:2.220412270429194, w2:1.0403956869540527, bias:-1.6922300262972403, loss:0.47013282006460577
Epoch:3450, w1:2.236352278196045, w2:1.04449496671828, bias:-1.7039704209807665, loss:0.469315154201496
Epoch:3500, w1:2.252156214369839, w2:1.0485576306341198, bias:-1.7156104583983194, loss:0.46851142227865256
Epoch:3550, w1:2.267825617378888, w2:1.0525843709890546, bias:-1.727151505832932, loss:0.4677213337863815
Epoch:3600, w1:2.2833620055033, w2:1.0565758623302701, bias:-1.7385949036124733, loss:0.46694460539365445
Epoch:3650, w1:2.298766877068819, w2:1.060532761875556, bias:-1.749941965884858, loss:0.46618096074405657
Epoch:3700, w1:2.3140417106537186, w2:1.0644557099300604, bias:-1.7611939813485655, loss:0.4654301302582344
Epoch:3750, w1:2.329187965305985, w2:1.0683453303056172, bias:-1.7723522139438943, loss:0.4646918509426179
Epoch:3800, w1:2.344207080768445, w2:1.0722022307399686, bias:-1.7834179035094793, loss:0.46396586620419994
Epoch:3850, w1:2.3591004777099505, w2:1.0760270033137527, bias:-1.7943922664078809, loss:0.4632519256711612
Epoch:3861, w1:2.3623602931863896, w2:1.0768641992956793, bias:-1.7967944891651444, loss:0.4630964507079002
Final weights and bias: w1:2.3623602931863896,w2:1.0768641992956793, bias: -1.7967944891651444